# ---
# Config file theme Everforest
# ---

[Ui]
name_theme = Everforest
bg = "#2d353b" # background
fg = "#d3c6aa" # text
selection = "#e67e80"

[Ui.statusline]
background = 
modes = {
    # First text color, second background color
    edit = ["#272e33", "#a7c080"],
    command = ["#272e33", "#dbbc7f"],
    search = ["#272e33", "#83c092"],
    files = ["#272e33", "#d3c6aa"],
    selection = ["#272e33", "#e67e80"],
    hotkeys = ["#272e33", "#d699b6"] 
}