# ---
# Claxis — Configuration demo file
# ---

[Themes]
path = "~/.config/editor/theme"

[General]
language = "ru"                                      # Enum > ru, en, uk...
color_modes = true
auto_format = true                                 # Enable automatic formatting on save
insert_final_newline = true


